flowchart LR
  Rol --- Usuario
  Usuario --- Pedido
  Mesa --- Pedido
  Pedido --- DetallePedido
  Pedido --- Venta
  Categoria --- Plato
  Menu --- DetalleMenu
  Plato --- DetalleMenu
  Combo --- DetalleCombo
  Plato --- DetalleCombo
  Compra --- DetalleCompra
  Producto --- DetalleCompra
